### ISSUE TITLE
Wrong result when taxable income becomes too large

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Income-Tax-Calcultor#10]
![image](https://user-images.githubusercontent.com/56196640/120814535-990f7900-c56c-11eb-8755-f520d2e18eed.png)

**Comment by Sakalya100** [comment]
I would like to contribute to this task. Please assign me this .

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by techabhi08** [comment]
I would like to contribute to this issue. @QAZIMAAZARSHAD please assign me this.

**Comment by tannu945** [comment]
I would like to contribute to this issue.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Since this is a bug, I'll merge only the first PR which will completely resolve this issue.

**Comment by ShreyaKanodia** [comment]
I would like to work on this issue.
I have figured out the bug . @QAZIMAAZARSHAD 
Please assign me this project under LGMSoC.

**Comment by QAZIMAAZARSHAD** [comment]
@ShreyaKanodia go ahead, I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Good job @ShreyaKanodia, I'll merge your PR tomorrow.
