### ISSUE TITLE
Another bug with close button

### ISSUE THREAD

**Issue by akash-rajak** [QAZIMAAZARSHAD/Income-Tax-Calcultor#103]
Earlier the exit dialog box ia appearing only when, exit button is clicked
means , this below button,
![1](https://user-images.githubusercontent.com/57003737/121905162-79840780-cd47-11eb-9024-313a089570b4.jpg)

but i think this exit dialog box must appear, even when tried to exiting(closing) the window using top right corner of main window,
means closing with this shown below,
![2](https://user-images.githubusercontent.com/57003737/121905930-3e360880-cd48-11eb-9a92-7223c0173a23.jpg)

So in this issue i want to implement the exit dialog box in  such a way ,that when we try to close the window, either by exit button  or top right corner cross button, the exit dialog box must appear every time.

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , please assign this to me under LGM SOC, to correct bug.

**Comment by QAZIMAAZARSHAD** [comment]
Great observation.
