### ISSUE TITLE
i label to see valid data

### ISSUE THREAD

**Issue by akash-rajak** [QAZIMAAZARSHAD/Income-Tax-Calcultor#107]
Want to add i label to showing eg. of  valid entry which can be entered, 
eg. valid names, valid number , valid email id

it will look like this, on clicking on i label, we get this information
![1](https://user-images.githubusercontent.com/57003737/121987702-a3c0de00-cdb6-11eb-89ed-575b03404541.jpg)

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , if this can be done , please assign me this under LGM SOC

**Comment by QAZIMAAZARSHAD** [comment]
Okk fine,  

But it is not that necessary so, decrease the size of the 'i' icon.

**Comment by akash-rajak** [comment]
ok
