### ISSUE TITLE
Minor Error in step 6 of readme file (contribution guidelines)

### ISSUE THREAD

**Issue by Shaishav0507** [QAZIMAAZARSHAD/Income-Tax-Calcultor#114]
Hey @QAZIMAAZARSHAD 
There is a minor Error in readme file in Contribution Guidelines section. Please assign it to me.
Thanks

**Comment by QAZIMAAZARSHAD** [comment]
What error?

**Comment by Shaishav0507** [comment]
Instead of master it should be main branch.

**Comment by QAZIMAAZARSHAD** [comment]
No, it's fine, it's different for a few.

**Comment by Shaishav0507** [comment]
@QAZIMAAZARSHAD it's giving error.
If you want the same I don't have any problem
