### ISSUE TITLE
Error in contribution guidelines 

### ISSUE THREAD

**Issue by Shaishav0507** [QAZIMAAZARSHAD/Income-Tax-Calcultor#117]
Hey @QAZIMAAZARSHAD 
There is a error in contribution guidelines.
In step 6 of contribution guidelines, it should be main instead of master
I'm attaching a screen shot of the error.

![Capture](https://user-images.githubusercontent.com/77338581/122214691-0524a200-cec8-11eb-9891-17fee59c5501.PNG)

**Comment by Shaishav0507** [comment]
@QAZIMAAZARSHAD 
Please assign it to me.
I will make the necessary changes.

**Comment by QAZIMAAZARSHAD** [comment]
@Shaishav0507 it is different for a few, depends what is the name of your branch main or master, a few of my repo has master repo as default so upstream master works fine, and upstream main gives error.
And vice-versa for few other repos.
