### ISSUE TITLE
Final logo not appeared

### ISSUE THREAD

**Issue by akash-rajak** [QAZIMAAZARSHAD/Income-Tax-Calcultor#121]
Want to correct this bug.

It is like when we click on check tax scheme, it opens new window, whose final logo is not same as other.
do i want to correc this.

below is the screenshot of bug,

![1](https://user-images.githubusercontent.com/57003737/122497373-de22b900-d00a-11eb-974a-b748d3a5e14e.jpg)

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , please assign this to me under LGM SOC, i can correct this bug

**Comment by QAZIMAAZARSHAD** [comment]
Okk,

Correct one more thing, the text in the title bar of learn more popup window is title, rename it to learn more.

**Comment by akash-rajak** [comment]
ok i will do it.
