### ISSUE TITLE
Another bug with sending with email

### ISSUE THREAD

**Issue by akash-rajak** [QAZIMAAZARSHAD/Income-Tax-Calcultor#126]
The bug is,
when we have entered the correct details and calculated, then if we click on share with email button, we get message like this,
![5](https://user-images.githubusercontent.com/57003737/122514717-0241c280-d02a-11eb-9e8e-a902f8e87aa1.jpg)

Now in this , the emails are sent in both cases, either we click on OK button or close the dialog box,
but it will work like this
if we click on OK then only it should share the details, otherwise if we close the dialog box, the details should not be shared.

So i want to correct this bug so that if we click on OK button then only it will send details.

And also while sending process is going on we get some print statement in the console, like this,
![6](https://user-images.githubusercontent.com/57003737/122515654-631dca80-d02b-11eb-8b8a-69628df7cb87.jpg)

 so instead of print statement we can show those using message box.

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , if this is OK, then please assign me this under LGM SOC, can correct all the above mentioned things.

**Comment by QAZIMAAZARSHAD** [comment]
Sure,

Also rename OK to "Send to email"

**Comment by akash-rajak** [comment]
Just want to tell that we can't change the text from OK or cancel to any other text we want  in the message box, as all the message box are predefined.
So we can't put our own text in button of message box
