### ISSUE TITLE
Create a pdf Generator at last

### ISSUE THREAD

**Issue by rammya29** [QAZIMAAZARSHAD/Income-Tax-Calcultor#132]
We can add a button at the last to download in the form of a pdf. Can we do that here?

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead.

PDF should include every detail, user details, and tax details.

And the logo of the application in PDF also.

**Comment by rammya29** [comment]
I am unable to download Splash Screen.gif. How to do it?

**Comment by QAZIMAAZARSHAD** [comment]
Can't understand

Are you not able to run the application?

**Comment by rammya29** [comment]
Yes, I am trying to run

**Comment by QAZIMAAZARSHAD** [comment]
Is the application opening?

**Comment by rammya29** [comment]
No sir, I am trying to run  in colab

**Comment by QAZIMAAZARSHAD** [comment]
> No sir, I am trying to run in colab

I never tried this application on colab.
Use idle.

Search your error on StackOverflow or reach out to mentors for help in the slack channel.

**Comment by rammya29** [comment]
for running I need that image splash screen.jpg. how to get it?

**Comment by QAZIMAAZARSHAD** [comment]
> for running I need that image splash screen.jpg. how to get it?

Just download the zip file.

You will get the entire folder. Take the images you need.

**Comment by rammya29** [comment]
Can anyone say how to upload image?

**Comment by QAZIMAAZARSHAD** [comment]
Use git. (Watch video on youtube)


Other way (shortcut) -> 
![image](https://user-images.githubusercontent.com/56196640/122870561-72628800-d34b-11eb-88e4-b23e53bc0346.png)
