### ISSUE TITLE
We can improve the UI of Tax Calculator page

### ISSUE THREAD

**Issue by Knighthawk-Leo** [QAZIMAAZARSHAD/Income-Tax-Calcultor#135]

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead.

But I will accept the changes only if I like it.

**Comment by QAZIMAAZARSHAD** [comment]
@Knighthawk-Leo any updates?

**Comment by Knighthawk-Leo** [comment]
> @Knighthawk-Leo any updates?

I am thinking that we can improve UI busing pyside or kivy module these are better than tkinter can I do that

**Comment by QAZIMAAZARSHAD** [comment]
This application is based on tkinter, don't use kivy or any other framework.

**Comment by QAZIMAAZARSHAD** [comment]
@Knighthawk-Leo should I close this issue or you are working on it?

**Comment by Knighthawk-Leo** [comment]
You can close the Issue.
