### ISSUE TITLE
Get message on generating PDF

### ISSUE THREAD

**Issue by akash-rajak** [QAZIMAAZARSHAD/Income-Tax-Calcultor#140]
When user clicks on the Generate PDF button the PDF gets generated in the folder of without giving any message.

So, want to add this message box showing message to user that Automated PDF generated successfully.

like this,

![1](https://user-images.githubusercontent.com/57003737/122942798-16702180-d394-11eb-9fd8-9a207c642113.jpg)

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , please assign this to me under LGM SOC, can add this message box.

**Comment by QAZIMAAZARSHAD** [comment]
This issue is already open https://github.com/QAZIMAAZARSHAD/Income-Tax-Calcultor/issues/137.
