### ISSUE TITLE
Removing unnecessary characters and changing keypad logo

### ISSUE THREAD

**Issue by akash-rajak** [QAZIMAAZARSHAD/Income-Tax-Calcultor#146]
In this i will modify the keypad button in such a way, that
in case of entering only alphabets will come ,
in case of phone numbers, exemption/deduction and income , keypad with only digits will popup
and in case of email if, keypad with alphabets, digits and extra character '@' and '.'  will popup.

And also change the keypad button to keypad logo.

below are screenshots :
In case of name,
![1](https://user-images.githubusercontent.com/57003737/123236347-58b37300-d4fa-11eb-97b1-a26805532f39.jpg)

In case of contact no.,
![2](https://user-images.githubusercontent.com/57003737/123236420-679a2580-d4fa-11eb-875a-09056d2f4129.jpg)

In case of email id ,
![3](https://user-images.githubusercontent.com/57003737/123236459-6ff26080-d4fa-11eb-8ada-459bbc3db69f.jpg)

and  in case of income and exemption/deduction,
![4](https://user-images.githubusercontent.com/57003737/123236539-813b6d00-d4fa-11eb-8a7f-e6f9ace9b5a4.jpg)

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , assign this to me under LGM SOC, can modify like this

**Comment by QAZIMAAZARSHAD** [comment]
decimal also in income and deductions.

**Comment by akash-rajak** [comment]
when we put decimal in income, it gives error message, like only integer is to be entered

**Comment by QAZIMAAZARSHAD** [comment]
> when we put decimal in income, it gives error message

okk fine
