### ISSUE TITLE
Update pull_request_template.md

### ISSUE THREAD

**Issue by manasb15** [QAZIMAAZARSHAD/Income-Tax-Calcultor#155]
This point in the checklist :

(I have added my name in the contributors list at the end of README.md file.)

is obsolete. So it is wise to remove it.

@QAZIMAAZARSHAD please assign this to me under DCP21

**Comment by QAZIMAAZARSHAD** [comment]
Yesterday you said it helps you in remembering git commands.

I want to tell, you can do these changes without using git quickly.
Just open the pull request template file in your repo, remove the line, commit changes, make PR. And its done.

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD Yes I know that method as well but I heard that it was like a shortcut or bad practice.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Yes I know that method as well but I heard that it was like a shortcut or bad practice.

Yaa in the case of many changes it causes difficulty in merging and few other problems like unnecessary indentations etc.

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD Ok then i will update it online for these small changes
