### ISSUE TITLE
Window can't be made to full screen or diminish it

### ISSUE THREAD

**Issue by Swethashub-source** [QAZIMAAZARSHAD/Income-Tax-Calcultor#162]
The total window for every screen we enter can't be enlarged using restore and minimize buttons on the right last corner

**Comment by QAZIMAAZARSHAD** [comment]
Yes.

If we enlarge or diminish the window size it will disturb the contents.

We can also arrange the content according to the window size but since there is not much content for large window size, the current size is fine.
