### ISSUE TITLE
Add hacktoberfest 2021 logo in Readme

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Income-Tax-Calcultor#163]
Add it in the Programs we have been associated with section.

**Comment by codewith-arijit** [comment]
Submitted my PR For Hacktoberfest 2021. Please assign it to me.

**Comment by QAZIMAAZARSHAD** [comment]
> Submitted my PR For Hacktoberfest 2021. Please assign it to me.

You have to first ask for an assignment then start working.


Fine.
No worries, I have merged your PR.
