### ISSUE TITLE
Make the size of window fixed so that full content is visible.

### ISSUE THREAD

**Issue by techabhi08** [QAZIMAAZARSHAD/Income-Tax-Calcultor#19]
If the user is resizing the window the content is disappearing. This can be fixed so that the screen size remains the same.

![Screenshot (410)](https://user-images.githubusercontent.com/75834097/121379947-20d8f700-c962-11eb-800e-74cbc2901a3c.png)
![Screenshot (411)](https://user-images.githubusercontent.com/75834097/121379956-233b5100-c962-11eb-902f-beaf1c7b345d.png)

**Comment by techabhi08** [comment]
@QAZIMAAZARSHAD please assign me this new issue that I have created or should I directly submit the result?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD please assign me this new issue that I have created or should I directly submit the result?

Go ahead @techabhi08.

I'll assign you this soon.

**Comment by techabhi08** [comment]
Thank you

**Comment by techabhi08** [comment]
@QAZIMAAZARSHAD I have solved this issue but whatever changes I am making to my github file and contributing it, it is committing changes in another issue and no pull request is being created for this one. How should I resolve this?

**Comment by QAZIMAAZARSHAD** [comment]
This should not happen.

Wait till I merge your previous PR, delete the latest commit in your PR you have done for this issue.

Once I merge that PR then generate a new PR by making changes for this issue, I hope that will solve the issue.

**Comment by techabhi08** [comment]
ok doing the same.

**Comment by techabhi08** [comment]
I have done the change can you please confirm. Also is that issue number #10 resolved by my PR?

**Comment by QAZIMAAZARSHAD** [comment]
> I have done the change can you please confirm. Also, is that issue number #10 resolved by my PR?

No issue 10 is not resolved by your PR. Improve your code before anyone else sends a better solution.

**Comment by techabhi08** [comment]
@QAZIMAAZARSHAD have you merged the PR can i create a new one now?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD have you merged the PR can I create a new one now?

No LGM-Soc will start from 10 June.
Also, your PR for the wrong result issue is not solving the issue so you can close that.

Your changes for this issue #19 are perfectly fine you can make PR for this one.

**Comment by techabhi08** [comment]
@QAZIMAAZARSHAD did you find the solution useful like is this issue resolved?

**Comment by QAZIMAAZARSHAD** [comment]
Yes, I will merge your PR tomorrow morning.

**Comment by techabhi08** [comment]
OK Thanks a lot.
