### ISSUE TITLE
Change logo in title bar 

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Income-Tax-Calcultor#2]
![image](https://user-images.githubusercontent.com/56196640/120801941-775bc500-c55f-11eb-9d9d-9bf1575320a0.png)

**Comment by Khushi-sharma07** [comment]
I want to contribute in this issue. Please assign it to me.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Khushi-sharma07** [comment]
Thank you!

**Comment by Khushi-sharma07** [comment]
Can you please tell that what should be the logo image after changing the default one?
And the logo should also change for the pop-up (tax-scheme)

**Comment by QAZIMAAZARSHAD** [comment]
@Khushi-sharma07 logo of this application is yet to be designed, see issue number https://github.com/QAZIMAAZARSHAD/Income-Tax-Calcultor/issues/7.

Wait till that issue gets soved.

**Comment by Khushi-sharma07** [comment]
Okay

**Comment by techabhi08** [comment]
@QAZIMAAZARSHAD can you assign this to me as well. I am interested in this

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD can you assign this to me as well. I am interested in this

@techabhi08 since this is a very basic issue I cannot assign it to more than one contributor.
Look for any other issues or open new issues.

**Comment by techabhi08** [comment]
ok

**Comment by jatinjain001** [comment]
I will like to work on it please assign it to me

**Comment by QAZIMAAZARSHAD** [comment]
> I will like to work on it please assign it to me

Already assigned to @Khushi-sharma07.

**Comment by Khushi-sharma07** [comment]
Now I think that "create the logo" pr is merged so I can also create the pr for this issue can you please tell me that which logo is finalised.

**Comment by Khushi-sharma07** [comment]
Actually I can see 3 pr merged for the issue.

**Comment by QAZIMAAZARSHAD** [comment]
Use this logo -> https://github.com/QAZIMAAZARSHAD/Income-Tax-Calcultor/blob/main/Logo/Income%20Tax%20calculator.png

**Comment by Khushi-sharma07** [comment]
Okay
