### ISSUE TITLE
Create live server link

### ISSUE THREAD

**Issue by Shaishav0507** [QAZIMAAZARSHAD/Income-Tax-Calcultor#20]
Hey @QAZIMAAZARSHAD 
Add the link in the description of the server live.
Thanks.

**Comment by QAZIMAAZARSHAD** [comment]
> Hey @QAZIMAAZARSHAD
> Add the link in the description of the server live.
> Thanks.

Do you mean, create a live server link of this application?

**Comment by Shaishav0507** [comment]
Yes if it's possible.
Because in description, repo link is there

**Comment by QAZIMAAZARSHAD** [comment]
If you know how to generate a live server link for this application then go ahead.

Ping me here, once you create that link.

**Comment by jigar-sable** [comment]
I think we can't deploy this project to live server as this is not a flask or django or any web application.
It's basic python program which needs virtual environment to run it. So this is not possible.

**Comment by QAZIMAAZARSHAD** [comment]
> I think we can't deploy this project to a live server as this is not a flask or Django or any web application.
> It's a basic python program that needs a virtual environment to run it. So this is not possible.

Yaa I already tried it I know.
But @Shaishav0507 opened this issue so I thought he might have some idea.

@Shaishav0507 if you also think it is not possible tell me I will close this issue.
But you have all the time to try.

**Comment by Shaishav0507** [comment]
@QAZIMAAZARSHAD 
I tried  https://shaishav0507.github.io/Income-Tax-Calcultor/
Its better than putting agian github repo link in description
If you feel like it is better than the current option, Please go ahead

**Comment by QAZIMAAZARSHAD** [comment]
Okk
