### ISSUE TITLE
Application not working fine in macOS

### ISSUE THREAD

**Issue by skimran2000** [QAZIMAAZARSHAD/Income-Tax-Calcultor#23]
There are few button issues
![Screenshot 2021-06-09 at 10 34 56 PM](https://user-images.githubusercontent.com/78163908/121402730-debab000-c977-11eb-990f-f12bcfd9cfbf.png)

**Comment by QAZIMAAZARSHAD** [comment]
@skimran2000 I'll review your PR soon.

**Comment by skimran2000** [comment]
okay

**Comment by skimran2000** [comment]
btw when i am trying to pull changes from upstream repo, I am getting an error:

command--> git pull upstream master
error-->          fatal: couldn't find remote ref master


Should it be --- git pull upstream main ?

**Comment by QAZIMAAZARSHAD** [comment]
Yaa try it.

Or google it this is a common issue.

**Comment by skimran2000** [comment]
I found another bug related to tax calculation. When annual income is less than deductions then also it is calculating the tax which is wrong because annual income should always be greater than deductions.
Once look into it if there is really a bug then i would like to raise an issue as i have corrected the error in code.

![Screenshot 2021-06-11 at 1 46 20 AM](https://user-images.githubusercontent.com/78163908/121621731-5ed13a80-ca8a-11eb-812c-b44d6d03391f.png)

**Comment by QAZIMAAZARSHAD** [comment]
Yes open this issue.

**Comment by skimran2000** [comment]
What should the title of issue be?

**Comment by QAZIMAAZARSHAD** [comment]
Wrong output when deductions become larger than income

**Comment by QAZIMAAZARSHAD** [comment]
This will not work.

Make a separate file for macOS users. And add it.

I will merge it.

**Comment by QAZIMAAZARSHAD** [comment]
@skimran2000 any updates?
