### ISSUE TITLE
Apply creative hover effect on all buttons

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Income-Tax-Calcultor#3]

**Comment by Kalyanjitdas** [comment]
hello sir I am interested in completing this task can you please assign me this task.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Kalyanjitdas** [comment]
Thankyou.

**Comment by skimran2000** [comment]
I am a LGM-SOC participant, can you please assign this issue to me

**Comment by QAZIMAAZARSHAD** [comment]
> I am a LGM-SOC participant, can you please assign this issue to me

Remember if you want your PR to be merged then your design should be better than the others.

**Comment by skimran2000** [comment]
okay

**Comment by skimran2000** [comment]
i have found an issue in the code with buttons

**Comment by skimran2000** [comment]
![Screenshot 2021-06-09 at 10 39 54 PM](https://user-images.githubusercontent.com/78163908/121400762-97cbbb00-c975-11eb-8f3f-627155de796d.png)

**Comment by skimran2000** [comment]
![Screenshot 2021-06-09 at 10 34 56 PM](https://user-images.githubusercontent.com/78163908/121400804-a74b0400-c975-11eb-8123-9c44e15791e6.png)

**Comment by skimran2000** [comment]
should i open a new issue?

**Comment by QAZIMAAZARSHAD** [comment]
> should I open a new issue?

I think something's wrong with your system.
You can see screenshots in the Readme file, buttons are fine.

Try to clone the project again.

**Comment by skimran2000** [comment]
i have cloned twice but still the same issue
mine is macos, i have fixed the issue

**Comment by QAZIMAAZARSHAD** [comment]
> I have cloned twice but still the same issue
> mine is macOS, I have fixed the issue

Okk, If you think everything's fine then open a new issue "Application not working fine in macOS".
I will review your PR and if it is fine I will merge it.

**Comment by skimran2000** [comment]
Okay

**Comment by jatinjain001** [comment]
I would like to work on it please assign it to me

**Comment by jatinjain001** [comment]
now you can view my PR. It has no conflicts
