### ISSUE TITLE
Add a Info/Learn more  Button 

### ISSUE THREAD

**Issue by shantamsultania** [QAZIMAAZARSHAD/Income-Tax-Calcultor#31]
There are some things that the user may not understand like what do we mean by old tax, New Tax what is the formula being used to calculate the Tax.

To resolve this issue I am thinking of adding an Info Button in the result window that will help the user understand what is the meaning of these things. 

#LGM-SOC

**Comment by QAZIMAAZARSHAD** [comment]
Nice idea @shantamsultania.

Go ahead.
