### ISSUE TITLE
clear button

### ISSUE THREAD

**Issue by akash-rajak** [QAZIMAAZARSHAD/Income-Tax-Calcultor#35]
Want to add a clear button beside the next button, so that if someone while entering details like name, contact, or email id, if he/she finds that he/she had written something wrong then, with clear button we can clear the data entered.
Using this clear button we don't need to manually delete the data entered.

for example , given screenshot of how button will look like
![clear](https://user-images.githubusercontent.com/57003737/121624922-14eb5300-ca90-11eb-9109-890cb62ea313.png)

In same way, also want to add clear between on third page also, while entering Annual Income and Exemptions / deductions.

for example,
![2](https://user-images.githubusercontent.com/57003737/121626398-fcc90300-ca92-11eb-9cb9-a021f369445a.png)

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , please assign this issue to me under LGMSOC. I would like to add this clear button on the second page of enetring details.

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , I have created a pull request
Also it is showing you have 3 conflicts , can you please guide me what this conflicts is about

**Comment by QAZIMAAZARSHAD** [comment]
@akash435 their have been some updates in the main file and your repository is behind those changes.

So first fetch upstream from the main repository. The issue will be resolved.
If not then contact mentor in the slack channel he/she will guide you.

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , I have closed all the previous pull request that have conflicts, and created a new pull request without any conflicts. Please check it.

**Comment by QAZIMAAZARSHAD** [comment]
Will review soon.
