### ISSUE TITLE
details button

### ISSUE THREAD

**Issue by akash-rajak** [QAZIMAAZARSHAD/Income-Tax-Calcultor#36]
Want to create a details button at the top of the third page, clicking on which we get the details entered by the user on the 2nd page, like his/her name, contact, email id.
And details will be displayed in form of message box.

for example,
I entered details like this,
![3](https://user-images.githubusercontent.com/57003737/121628772-88449300-ca97-11eb-8ff7-91183db2c149.png)

then on clicking on the next button, we see a details button on the top, clicking on which gives us information about user in message box, like this,
![1](https://user-images.githubusercontent.com/57003737/121639296-f72ae780-caa9-11eb-86e2-8309066c6857.png)

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , please assign this issue to me under LGMSOC. I would like to add this details button showing the details of the user on the top of third page.

**Comment by Khushijindal24** [comment]
sir i want to contribute in this issue please assign me this.

**Comment by QAZIMAAZARSHAD** [comment]
Okk,

but shift the user details box beside credits not at the top.
And change button name to user details.

**Comment by QAZIMAAZARSHAD** [comment]
> sir i want to contribute in this issue please assign me this.

Ok,

remember only the first and the better solution will be accepted.

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , Sir i have created my pull request for User details button, please check it

**Comment by QAZIMAAZARSHAD** [comment]
Will review soon.
