### ISSUE TITLE
Wrong output when deductions become larger than income

### ISSUE THREAD

**Issue by skimran2000** [QAZIMAAZARSHAD/Income-Tax-Calcultor#40]
The output is wrong when the deductions amount become larger than the annual income
![Screenshot 2021-06-11 at 1 46 20 AM](https://user-images.githubusercontent.com/78163908/121656824-8261a880-cabd-11eb-8a6d-a24ed85828d3.png)

**Comment by skimran2000** [comment]
Issue is not been assigned to be

**Comment by skimran2000** [comment]
Do you want the issue solved with my previous macOS update or for normal code
I mean should this issue be resolved with my code containing the macOS resolved code or for your code, since my previous PR is still on hold

**Comment by QAZIMAAZARSHAD** [comment]
> Do you want the issue solved with my previous macOS update or for normal code

I reviewed you macos update but then application was not working in my system.
I'll try to review it once again.


Always make changes to the updated repository, so don't include your macOS updates.

**Comment by skimran2000** [comment]
have you installed the tkmacosx library which i have used
pip3 install tkmacosx

and also have you tried reviewing it in macOS device?

**Comment by QAZIMAAZARSHAD** [comment]
I don't have macOS device.

**Comment by QAZIMAAZARSHAD** [comment]
Fine,


But still a little issue.
![image](https://user-images.githubusercontent.com/56196640/121708972-b1940c00-caf5-11eb-8f10-03f1594dbb23.png)

Go open a new issue and fix this also.

**Comment by skimran2000** [comment]
okay
i have done a mistake in variable name i.e 'tax_save' as 'tax_sav'

i have found another coding mistake in your code:
**'at' is passed instead of 'ta'**

Please say me the issue title to open and rectify the above mistakes

![Screenshot 2021-06-12 at 11 13 08 AM](https://user-images.githubusercontent.com/78163908/121766453-79311400-cb6f-11eb-9de3-e4fd0c3bdb0b.png)

**Comment by QAZIMAAZARSHAD** [comment]
> okay
> i have done a mistake in variable name i.e 'tax_save' as 'tax_sav'
> 
> i have found another coding mistake in your code:
> **'at' is passed instead of 'ta'**
> 
> Please say me the issue title to open and rectify the above mistakes
> 
> ![Screenshot 2021-06-12 at 11 13 08 AM](https://user-images.githubusercontent.com/78163908/121766453-79311400-cb6f-11eb-9de3-e4fd0c3bdb0b.png)

You can open an issue with any name.
I will rectify the title if it is not fine.

You can open issue.
