### ISSUE TITLE
Change cursor to pointer when hovering on buttons

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Income-Tax-Calcultor#5]

**Comment by Kalyanjitdas** [comment]
hello! I am interested in completing this task. Can you please assign me the task.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Kalyanjitdas** [comment]
ok thankyou for giving me this opportunity.

**Comment by Prateek027-S** [comment]
I want to contribute to this project by solving this issue. Please assign me the task.

**Comment by QAZIMAAZARSHAD** [comment]
@Prateek027-S since this is an easy issue I cannot assign it to more than one person.

You can look for any other issue or open new issues.

**Comment by Prateek027-S** [comment]
@QAZIMAAZARSHAD Okay. No problem.

**Comment by jigar-sable** [comment]
Hii, I want to work on this issue please assign me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@jigar-sable I will review your PR soon.
