### ISSUE TITLE
Add links to these gifs

### ISSUE THREAD

**Issue by Umesh-01** [QAZIMAAZARSHAD/Income-Tax-Calcultor#51]
I think these two gifs (see the below image) should contain a links to the related files because there are the chances the anyone can click on them and these are of no use. So it must redirect us to the pages where these files are present.
 
![image](https://user-images.githubusercontent.com/83420185/121710061-d046d280-caf6-11eb-98f0-36ce97313a70.png)

**Comment by Umesh-01** [comment]
@QAZIMAAZARSHAD Should I do these changes??

**Comment by QAZIMAAZARSHAD** [comment]
Sure.

**Comment by QAZIMAAZARSHAD** [comment]
Nothing has changed.

On clicking images it should direct to code of conduct and license page

**Comment by Umesh-01** [comment]
> Nothing has changed.
> 
> On clicking images it should direct to code of conduct and license page

Yes it was working

**Comment by Umesh-01** [comment]
@QAZIMAAZARSHAD wait let me check...

**Comment by Umesh-01** [comment]
Hey @QAZIMAAZARSHAD what that revert PR means??

My PR is working I checked it

Check it here--
https://github.com/QAZIMAAZARSHAD/Income-Tax-Calcultor/pull/52/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

Here in rich difference you can check, now when clicking on gifs it is taking us to the related page....

**Comment by Umesh-01** [comment]
@QAZIMAAZARSHAD sir why this is open, my PR is working...

**Comment by Umesh-01** [comment]
sir my contributiion  is working na??

it will be counted??

**Comment by QAZIMAAZARSHAD** [comment]
> sir my contributiion is working na??
> 
> it will be counted??

yes absolutely

**Comment by Umesh-01** [comment]
> > sir my contributiion is working na??
> > it will be counted??
> 
> yes absolutely

thank u sir... 🙂

**Comment by QAZIMAAZARSHAD** [comment]
You can open the same issue in my other two projects, movie streaming website and voters registration portal.

If you want to earn more points.

**Comment by Umesh-01** [comment]
Okk sir, thanks for the suggestion.. 🙂 
I will do it now...
