### ISSUE TITLE
Changing Screenshot of Readme File

### ISSUE THREAD

**Issue by akash-rajak** [QAZIMAAZARSHAD/Income-Tax-Calcultor#54]
Want to change the screenshot of readme file, as new buttons are added in gui window.

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , Are we able to do this kind of changes in readme or we are only allowed to do changes in code only?
If yes, then please assign me

**Comment by QAZIMAAZARSHAD** [comment]
Sure, update the screenshots.

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , I have updated the screenshots in readme file with new screenshots of the updated code. Please check it.
