### ISSUE TITLE
Disable maximize/minimize window option in "Check Tax Scheme" pop-up

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Income-Tax-Calcultor#6]
![image](https://user-images.githubusercontent.com/56196640/120803997-c571c800-c561-11eb-8fda-028bbe7ada34.png)

👆 This is the result when maximizing the "Check Tax Scheme" window. 
Disable it, like it is in main window.

**Comment by Khushi-sharma07** [comment]
Please assign me this issue when the event begins. I want to contribute to it.

**Comment by Sakalya100** [comment]
Please assign this to me. I want to contribute to this.

**Comment by QAZIMAAZARSHAD** [comment]
@Khushi-sharma07 I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

@Sakalya100 since this is an easy issue I cannot assign it to more than one person, if this issue remains unresolved then I will assign you.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Khushi-sharma07** [comment]
Thank you!

**Comment by Sakalya100** [comment]
Thank You

**Comment by QAZIMAAZARSHAD** [comment]
Good job @Khushi-sharma07.

I'll merge your PR tomorrow.

**Comment by Khushi-sharma07** [comment]
Thank you so much! @QAZIMAAZARSHAD
