### ISSUE TITLE
Documentation - Add badges in readme

### ISSUE THREAD

**Issue by jigar-sable** [QAZIMAAZARSHAD/Income-Tax-Calcultor#60]
**Add the following badges in the readme file on top:**
- Issue count
- Star count
- Fork count
- Slack channel link

On click, these badges should open respective pages.

### Additional Context
[shields.io](https://shields.io/) can be used for generating the badges.

### Example
![image](https://user-images.githubusercontent.com/64949957/121765200-d2e11080-cb66-11eb-9c96-f56b74c1523f.png)
![image](https://user-images.githubusercontent.com/64949957/121765211-ec825800-cb66-11eb-9167-cbd00fbcbc11.png)

**Comment by QAZIMAAZARSHAD** [comment]
Sure.
