### ISSUE TITLE
Providing email id with proper format

### ISSUE THREAD

**Issue by dhruv-varshney** [QAZIMAAZARSHAD/Income-Tax-Calcultor#62]
If the user enters any character other than abc@xyz.com then it does not return any error. It should provide an error like provide proper email id.

**Comment by QAZIMAAZARSHAD** [comment]
> If the user enters any character other than [abc@xyz.com](mailto:abc@xyz.com) then it does not return any error. It should provide an error like provide proper email id.

This issue was already open and has been resolved now.

Before opening any issue make sure that no other similar issue is open.
