### ISSUE TITLE
Mail the details to user about tax calculated 

### ISSUE THREAD

**Issue by Khushijindal24** [QAZIMAAZARSHAD/Income-Tax-Calcultor#63]
Sir can i make a mail button .when user will click on it ,it will display the users information with tax calculated for confirmation and then when we will click on ok it will mail that info to user so that in future user can have his tax details using sendgrid or some third party api to send mail.

**Comment by QAZIMAAZARSHAD** [comment]
Great idea.

Go ahead.

**Comment by Khushijindal24** [comment]
Hi ,I'm done with functionality I just need a gmail account to link too.

**Comment by QAZIMAAZARSHAD** [comment]
> Hi ,I'm done with functionality I just need a gmail account to link too.

I think all the details should be mailed to the user who is using the calculator.

**Comment by Khushijindal24** [comment]
> > Hi ,I'm done with functionality I just need a gmail account to link too.
> 
> I think all the details should be mailed to the user who is using the calculator.

In order to send the mail we need to add a email and password at our code,than only our service will work

**Comment by QAZIMAAZARSHAD** [comment]
Use your email.
Or create a new one.
Or use a one-time email there are many websites that give temporary emails.

**Comment by Khushijindal24** [comment]
sir I dont have access to push the code in my branch (branch name: khushi)
I am done with the code please provide me the access

**Comment by QAZIMAAZARSHAD** [comment]
> sir I don't have access to push the code in my branch (branch name: Khushi)
> I am done with the code please provide me the access

I don't have that right, you are independent to do all changes in your branch.
Google the query you may get the solution.
Or reach mentors in the slack channel.

**Comment by Khushijindal24** [comment]
sir I have generated pull request please check
