### ISSUE TITLE
Add News & Updates button

### ISSUE THREAD

**Issue by akash-rajak** [QAZIMAAZARSHAD/Income-Tax-Calcultor#68]
Want to add News and Updates button at top of the starting page
Clicking on this button will take us to website showing latest news and updates of income tax related.

Below is the screenshot, how it look like,
![1](https://user-images.githubusercontent.com/57003737/121769934-ff575580-cb83-11eb-9483-438bd133f9b4.png)

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , please assign me this under LGM SOC, want to add News & Updates button, on the starting page.

**Comment by QAZIMAAZARSHAD** [comment]
No need of news and updates in calculator.
