### ISSUE TITLE
Design a logo for this application

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Income-Tax-Calcultor#7]
This logo is to be used in the splash screen and title bar.

**Comment by Sakalya100** [comment]
Hello @QAZIMAAZARSHAD . Kindly assign this issue to me. I would like to contribute to this issue.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Sakalya100** [comment]
Thank you

**Comment by techabhi08** [comment]
Hi @QAZIMAAZARSHAD i would like to contribute to this issue. Please assign me this issue.

**Comment by SahityaRoy** [comment]
Hii @QAZIMAAZARSHAD  i wanna work with this logo shall i

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by ambivert-sam** [comment]
Hey, @starrohan999 I'm a participant of LGMSOC'21 ​I would like to contribute to this issue will you please assign it to me

**Comment by QAZIMAAZARSHAD** [comment]
Nice @Sakalya100.

But don't make PR's now.
Others are also working on this issue let's see their designs as well. The best will be accepted.

**Comment by Sakalya100** [comment]
Okay...So what should I do after making the logo. When Can I make the PR. Can you please tell @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
When everyone is done with their logo designs and your design is the best then I will inform you to make PR.

**Comment by kshitija-2001** [comment]
I would like to work on this issue. please assign it to me under LCM Soc21.

**Comment by QAZIMAAZARSHAD** [comment]
Everyone @kshitija-2001, @Sakalya100, @SahityaRoy, @ambivert-sam, @techabhi08  who have designed their logo can make PR now.

Create a folder named logo and add your logo in that folder.
No change in code,

**Comment by priyanshi5** [comment]
I would like to work on this issue. please assign it to me under LCM Soc21.

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue. please assign it to me under LCM Soc21.

Issue already resolved.
