### ISSUE TITLE
Modify Contributors in README

### ISSUE THREAD

**Issue by jigar-sable** [QAZIMAAZARSHAD/Income-Tax-Calcultor#76]
- As there was one point in PR template that added yourself as a contributor in readme so that I've made it in tabular format and comment is also there if someone wants to add.

![image](https://user-images.githubusercontent.com/64949957/121774499-4bb08e80-cba0-11eb-920f-3c2133c4364b.png)

**Comment by QAZIMAAZARSHAD** [comment]
Don't add the project admin section again.

Update only the contributors section.

**Comment by jigar-sable** [comment]
> Don't add the project admin section again.
> 
> Update only the contributors section.

Sure

**Comment by jigar-sable** [comment]
![image](https://user-images.githubusercontent.com/64949957/121784118-b6c58980-cbcf-11eb-81d2-546c33207f17.png)

- **Should I update it.. I'll not add it again, just few changes..**

**Comment by QAZIMAAZARSHAD** [comment]
Okk

**Comment by QAZIMAAZARSHAD** [comment]
Don't change pic
