### ISSUE TITLE
Create a pop-up when exiting application

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Income-Tax-Calcultor#8]
![image](https://user-images.githubusercontent.com/56196640/120808493-c0fbde00-c566-11eb-8c52-a7738e992eaa.png)

**Comment by Khushi-sharma07** [comment]
I want to contribute in this issue. Please assign it to me.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Khushi-sharma07** [comment]
Thank you!

**Comment by techabhi08** [comment]
I want to contribute to this issue. Please assign me this one.

**Comment by Prateek027-S** [comment]
I want to solve this issue. Please assign me the task.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Since many contributors are willing to resolve this issue only the best solution/design will be accepted.

**Comment by Khushijindal24** [comment]
i want to contribute in this issue.please assign me this task

**Comment by QAZIMAAZARSHAD** [comment]
> I want to contribute to this issue. please assign me this task

@Khushijindal24 this issue has already been resolved see pull request https://github.com/QAZIMAAZARSHAD/Income-Tax-Calcultor/pull/13. 
I'll merge this request tomorrow which will close this issue. You can always open another issue to improve the design if you have any better idea.

**Comment by Khushijindal24** [comment]
ok sir

**Comment by shashwat-2077** [comment]
@QAZIMAAZARSHAD sir please assign this issue to me

**Comment by Itashamodi** [comment]
i want to do this, assign me this kindlly

**Comment by QAZIMAAZARSHAD** [comment]
> I want to do this, assign me this kindly

@Itashamodi this issue has already been resolved by @shashwat-2077 and it will be closed soon.
You can look for any other issues or open a new one.
