### ISSUE TITLE
Code formating

### ISSUE THREAD

**Issue by shantamsultania** [QAZIMAAZARSHAD/Income-Tax-Calcultor#88]
I have a Suggestion to make to reformate the code to standard naming conventions for python.

Reason :

Many of the participants are beginners so I think it will be good if we can reformate the code to some extent like some variables are named f1,f2, and so on we can convert the name to frame1,frame2, and so on.

If possible can i can take this to make the code more readable? under LGM-SOC-21

**Comment by QAZIMAAZARSHAD** [comment]
Sure
