### ISSUE TITLE
Add Age as a new Paramenter

### ISSUE THREAD

**Issue by shantamsultania** [QAZIMAAZARSHAD/Income-Tax-Calcultor#89]
As we know age is a crucial parameter while calculating once taxes with the addition of age we can get more relief so i was thinking to add age as a parameter and update the tax calculations also

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead

**Comment by Lovishk022** [comment]
I also want to work on that, Pls assign me this issue @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> I also want to work on that, Pls assign me this issue @QAZIMAAZARSHAD

Okk go ahead.

But remember first and the better solution will be accepted.

**Comment by QAZIMAAZARSHAD** [comment]
@shantamsultania and @Lovishk022 are you guys working on it?

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , can you please tell me like in this adding age as a new parameter means what?. So that i can try for doing this issue.

**Comment by QAZIMAAZARSHAD** [comment]
​​​Senior citizens and very senior citizens are granted a higher exemption limit as compared to normal taxpayers. 

Study the rules for this.
And implement this in the application for a certain age group tax calculation should be different.

**Comment by QAZIMAAZARSHAD** [comment]
Should I assign you are you willing to take the challenge?

**Comment by akash-rajak** [comment]
Means we have to take age of the tax payer also as an input along with name, email id, and contact no. and calculate the tax according to age also.
like for senior citizen we have to use higher exemption limit.

If this is, then you  can assign me?

**Comment by QAZIMAAZARSHAD** [comment]
> Means we have to take age of the tax payer also as an input along with name, email id, and contact no. and calculate the tax according to age also.
> like for senior citizen we have to use higher exemption limit.
> 
> If this is, then you can assign me?

Yes.

But add age input on the tax calculation page.
Not with name, email, etc.

**Comment by QAZIMAAZARSHAD** [comment]
Under LGMSoC or DCP?

**Comment by akash-rajak** [comment]
LGM SOC

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD I searched a lot for this but didn't able to get any website with tax calculation with ages.
So you can unassign me from this.

Also  want to ask if we can add something like text to speech, like user can also have option to get speech output , then i can create an issue for this?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I searched a lot for this but didn't able to get any website with tax calculation with ages.
> So you can unassign me from this.
> 
> Also want to ask if we can add something like text to speech, like user can also have option to get speech output , then i can create an issue for this?

Sure if you can do this?

You can also work on the other issues which are already open https://github.com/QAZIMAAZARSHAD/Income-Tax-Calculator/issues/123 and https://github.com/QAZIMAAZARSHAD/Income-Tax-Calculator/issues/157.
