### ISSUE TITLE
Reset button not vanishing income/deductions input

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Income-Tax-Calcultor#9]
On clicking the reset button only the output is reset, no effect on input values.

**Comment by deek121477** [comment]
I would like to work on this issue. Could you please assign me?

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Prateek027-S** [comment]
I want to solve this issue. Please assign me this task.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Since this is a bug, I'll merge only the first PR which will completely resolve this issue.

**Comment by ShreyaKanodia** [comment]
I have figured out a solution .
Please assign me the task @QAZIMAAZARSHAD for LGMSoC

**Comment by QAZIMAAZARSHAD** [comment]
@ShreyaKanodia go ahead, I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by dhruv-varshney** [comment]
Hello @QAZIMAAZARSHAD  i think I can resolve this issue .may you assign me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> Hello @QAZIMAAZARSHAD i think I can resolve this issue .may you assign me @QAZIMAAZARSHAD

No need now, because we now have a clear button to do the work.
