### ISSUE TITLE
add multiple Share parameters 

### ISSUE THREAD

**Issue by shantamsultania** [QAZIMAAZARSHAD/Income-Tax-Calcultor#90]
recently I saw that one of the participant had included a share option to email 
what I am thinking is to add a multiple share option as we have in our phones nowadays like share to : email, Whatsapp, and others 

currently, I have these in mind 

1. WhatsApp 
2. email 
3. friend through message 
4. SMS to contact provided 

will try to think of more options also.

**Comment by QAZIMAAZARSHAD** [comment]
Sure

**Comment by QAZIMAAZARSHAD** [comment]
@shantamsultania any updates?
